### ISSUE TITLE
Update to ApiX

### ISSUE THREAD

**Issue by Nyakaze** [PrincessRTFM/XIVComboPlugin#102]
Hey,

I love this plugin and also relay a bit on it.
Is there a timeframe where u think u could update it to the new ApiX?

Thanks in advance! 💜

**Comment by PrincessRTFM** [comment]
Dalamud is still in private beta and isn't actually released as stable yet. Once that happens, I'll be able to test the PR that Terrorblade submitted, and assuming it all still works (I'm sure they tested it, but I don't want to risk Dalamud changing anything before the public release) then I should be able to get a minimally functional update out fairly quickly.

Please note that when I say _minimally functional_, I mean that any replacers that take more than a cursory tweak or two at most in order to fit the game's changes will be disabled, and **no new actions will be supported** until I have time to go over things in more detail.

**Comment by PrincessRTFM** [comment]
The API update is done, now we're just working on the details, like making sure we don't replace anything with disabled buttons and finding the new IDs. The update will be released as soon as we're (mostly) confident nothing will break. Your patience is appreciated!
