### ISSUE TITLE
Possibility to add a suggestion for Warrior?

### ISSUE THREAD

**Issue by Spanglish1337** [PrincessRTFM/XIVComboPlugin#19]
As a suggestion, can an option be added to have the end of Storm's Path chain, change to Storm's Eye, if the Surging Tempest buff have 7 seconds or less, and not active? If I am explaining myself correctly.

**Comment by PrincessRTFM** [comment]
The only part I don't understand is the "and not active" bit. What I'm otherwise understanding from your comment is that you want an option that will override the Storm's Path combo to become Storm's Eye instead, when the Surging Tempest buff is either not currently up _or_ has less than seven seconds remaining on it. That makes sense, although I'll mention that it _does_ carry the risk of leaving you unable to use Storm's Path to self-heal when you might need it.

Please let me know if that's what you're looking for or if I've missed something, but if that _is_ what you want, then I can do it easily enough.

**Comment by Spanglish1337** [comment]
Oh, I am sorry! I apologize, I do meant "When it is not currently up" as you mention. Like the monk one where it casts Twin Snakes (the buff) when it is not currently up. 

Mm... now that you mention it, Storm's path does give a nice self-heal, but I believe Warrior has enough instant self-sustain with their other CD's including Bloodwhetting.

I think I would like to test having that option, if possible, it would help me greatly anyway if the combos can be adjusted to be used with 1 button. I believe a good timing would be to change it to Storm's Eye one if the buff has 7 seconds or less, or it is not currently up.

Thank you for taking your time to read my request.
