### ISSUE TITLE
DRK Overcap missing

### ISSUE THREAD

**Issue by Iaotle** [PrincessRTFM/XIVComboPlugin#2]
Feature doesn't work, as far as I can tell.

**Comment by Iaotle** [comment]
https://github.com/PrincessRTFM/XIVComboPlugin/pull/3 made a PR for it. Should fix the issue.

**Comment by PrincessRTFM** [comment]
I'm going through the entire plugin to update it for EW right now, so this should be fixed in the next release. Unfortunately, that might take a little while - there's a lot to update. I'm hoping to at least have an alpha build able to compile this weekend. If it's still broken in the new release, let me know.
