### ISSUE TITLE
Warrior skill not changing to spender when overcapping

### ISSUE THREAD

**Issue by Spanglish1337** [PrincessRTFM/XIVComboPlugin#22]
![image](https://user-images.githubusercontent.com/89648547/154769287-89d49e03-2995-4539-8458-965dedff9cde.png)

"Replace the Storm's Path Combo with gauge spender if completing the combo would overcap you" Does not work since update.

In other notes, MNK works the same so far, no issues!

**Comment by Spanglish1337** [comment]
Bump! Hope you are doing okay in these harsh times, Princess.

**Comment by PrincessRTFM** [comment]
I'll take a look when I get the chance, I just got my computer working again after it being broken for a week.

**Comment by Spanglish1337** [comment]
No problem, take your time! Glad to hear you are doing well, PrincessRTFM!

**Comment by PrincessRTFM** [comment]
Finally got things working again (I hope) and I'm looking into this. It looks like everything will work, _provided_ you're level 70 or above, which... is either a holdover or a bug, I think. For some reason, I'm checking if your level is high enough for Inner Release, which I think is probably a bug because I forgot to fix that line. I'll update and release it, but can you confirm that your WAR level is _below_ 70 with things not working correctly?

**Comment by Spanglish1337** [comment]
Oooh okay that makes sense. My warrior is level 59.

**Comment by Spanglish1337** [comment]
Below level 59 and not working as intended, that is correct.

**Comment by Spanglish1337** [comment]
I meant, below level 70 and not working as intended, that is correct. My warrior is level 59.
