### ISSUE TITLE
Feature Request - Steel Peak/The Forbidden Chakra

### ISSUE THREAD

**Issue by Evolutious** [PrincessRTFM/XIVComboPlugin#28]
Good day! Would you mind please adding a new feature to the MNK section that will change Dragon Kick into Meditation when in combat and you have the Fifth Chakra open? This will result in executing Steel Peak/The Forbidden Chakra since Meditation changes into Steel Peak/The Forbidden Chakra when you have the Fifth Chakra open as part of a class trait.

Feature Name: Steel Peak/The Forbidden Chakra Feature
Description: Replace Dragon Kick with Meditation when in combat and the Fifth Chakra is open to use Steel Peak/The Forbidden Chakra

All that should be required in the main combo is an addition to the `internal class MonkDragonKick: CustomCombo` section adding the following lines:
`if (IsEnabled(CustomComboPreset.MonkDragonKickSteelPeakFeature)) {`
`    if (level >= MNK.Levels.Meditation && gauge.Chakra == 5 && InCombat)`
`        return MNK.Meditation;`
`}`

You will need to also add "MonkDragonKickSteelPeakFeature" option in CustomComboPreset.

**Comment by PrincessRTFM** [comment]
Can do, although since you went to the effort of writing the code, I just wanted to let you know two things:

1. You can use three backticks (the "\`" character) together to make a code block, and can put the name of the language right after the first three before the line break in order to do syntax highlighting!
2. Your `return MNK.Meditation` line needs to be `return OriginalHook(MNK.Meditation)` so that Meditation changes into Steel Peak / The Forbidden Chakra as normal, otherwise it'll only become Meditation itself.

Final code (and code block example) becomes:
```cs
if (IsEnabled(CustomComboPreset.MonkDragonKickSteelPeakFeature)) {
	if (level >= MNK.Levels.Meditation && gauge.Chakra == 5 && InCombat)
		return OriginalHook(MNK.Meditation);
}
```

#TheMoreYouKnow! :P

**Comment by Evolutious** [comment]
This works soooo good! Thank you! :D
