### ISSUE TITLE
MNK - Masterful Blitz

### ISSUE THREAD

**Issue by JackMaiden** [PrincessRTFM/XIVComboPlugin#29]
With no options set for Monk in the setup, Masterful Blitz is using the Monk AOE Combo setting, with no options selected I would expect the class to be as without the plugin. 

![image](https://user-images.githubusercontent.com/1594105/159136312-5c7b18f3-04c6-4346-a2fe-cb002cacb5ac.png)
![image](https://user-images.githubusercontent.com/1594105/159136323-6c2471ed-8c67-4ff4-b740-b3a69ecf9eb3.png)
![image](https://user-images.githubusercontent.com/1594105/159136331-b7b9d9ed-a15b-4dbb-a70e-5df481730cda.png)

**Comment by Spanglish1337** [comment]
Can you expand on what do you mean? Masterful Blitz indeed uses the AoE combo, 3 of the same for one of the nadis, and 3 different for the one that is missing.

If you use Masterful Blitz, on single target, you do require to do the Opo Opo, Raptor and Coeurl attacks manually. 

If you have the options of the combos enabled, you can do Perfect Balance > 1 > 2 > > 3 and then press Masterful Blitz for Phoenix attack and also Perfect Balance > 1 > 1 > 1 for Elixir Field. 

Is this what you mean? I want to understand because MNK has been working fine for me so far in all the ways so far.

**Comment by Evolutious** [comment]
Looks like a simple oversight when PrincessRTFM remade the function.

Just needs to change 
```c#
public override CustomComboPreset Preset { get; } = CustomComboPreset.MnkAny;
``` 
with 
```c#
public override CustomComboPreset Preset { get; } = CustomComboPreset.MonkAoECombo;
```

I am certain they will get it corrected soon ;)

**Comment by JackMaiden** [comment]
Also have noticed it occur on dragoon as well, cant remember exactly which skills unfortunately

**Comment by PrincessRTFM** [comment]
Found the Dragoon one, it's Coerthan Torment (which is turning into Doom Spike by default). I'll have both fixes up in a few.
