### ISSUE TITLE
MNK - Addressing Masterful Blitz for the AoE Combo

### ISSUE THREAD

**Issue by Evolutious** [PrincessRTFM/XIVComboPlugin#35]
Hi @PrincessRTFM - After you made the change for me to Perfect Balance (Thank you again! It is working perfectly!), to change it into Masterful Blitz while under the Perfect Balance buff (and not having 3 Beast Chakras open), I noticed that pressing the Perfect Balance button during this state will result in performing the AoE Combo, since that feature is using Masterful Blitz as the proxy action and only reverts back to Masterful Blitz if all 3 Beast Chakras are open.

What I am proposing is changing the MonkAoECombo to use Arm of the Destroyer, or Rockbreaker, as the proxy action instead of Masterful Blitz since AotD is the first AoE ability you learn and Rockbreaker is the second and both are actions exclusive to AoE. The rest of the MonkAoECombo feature should be fine, although I can see some additional opportunities to further refine that feature for low level players ;)

Was there a reason you changed to using Masterful Blitz that I am not thinking of? The only potential thing I could think of is if you are seeing an issue with using Arm of the Destroyer due to it changing into Shadow of the Destroyer once you hit the level for the trait to cause this. If that is the case, then Rockbreaker should suffice.

Just change:
~~~C#
public override uint[] ActionIDs { get; } = new[] { MNK.MasterfulBlitz };
~~~

to
~~~C#
public override uint[] ActionIDs { get; } = new[] { MNK.ArmOfTheDestroyer };
~~~
or
~~~C#
public override uint[] ActionIDs { get; } = new[] { MNK.Rockbreaker };
~~~

Nothing else should be needed to be changed. I am happy to test this out if you want to give it a go.

Thoughts?

**Comment by PrincessRTFM** [comment]
The reason for not using Rockbreaker is that apparently - and I never saw this, only heard reports from users - something in the game itself seemed to be caching wrongly and the combo would stick on Rockbreaker, not changing for a couple of seconds. I can try and revert it to RB if _necessary_, but I'd like to try AotD/SotD first, and both should be workable since I can just put both of them in the `ActionIDs` array. If it fails in some way, please reopen this issue, and I'll... probably see about providing user options for the replaced action, at that point.

**Comment by Evolutious** [comment]
Initial testing shows that it works perfect for me. this also means that Perfect Balance does not perform the AoE combo as well, so for me this is a W! :D

I will advise if I ever run into any issues, but we are good for the time.

btw; i am using Arm of the Destroyer as the action i am using in my macro.

**Comment by Evolutious** [comment]
One slight thing that I noticed with this; the feature in the /pcombo UI still says "Replaces Masterful Blitz with the AoE combo chain". That probably should be changed to "Replaces Arm of the Destroyer/Shadow of the Destroyer with the AoE combo chain" as to not confuse people.

**Comment by Grammernatzi** [comment]
Both me and Daemitus tried this before and it creates bugs with queueing. Specifically, in this case, it causes queueing issues before Shadow of the Destroyer in Perfect Balance. You may use it if you do not mind this, of course.

**Comment by PrincessRTFM** [comment]
Monk is my least favourite job to work on, and shit like this is why.

I might end up making the replaced action a user-selectable option, so people can choose what flavour of bug they're willing to live with.

**Comment by Grammernatzi** [comment]
Probably the best idea. This does affect more than just MNK, but MNK's weird combo system is most prone to it. You could also make it some sort of action that's useless on MNK, too, like a PLD action or something. But then that'd require them having to add the action onto their hotbar via ReAction or the like.

**Comment by Evolutious** [comment]
Honestly, with the most recent change that SE made to Perfect Balance, you can likely go back to using Masterful Blitz since Perfect Balance now has an internal check that if you have at least 1 Beast Chakra active, you are not able to use Perfect Balance again, which more or less is what the Perfect Balance change request was doing.

So if you want to go back to using Masterful Blitz and removing the feature to change Perfect Balance to Masterful Blitz while under the Perfect Balance buff, this should work fine now.

I know, 2 steps forward, 2 steps back... Whatever you decide, I will work around it as I have.

I do wonder, however, if the reason i do not experience any queuing bugs is because i use a mod that "corrects" queuing for things like macros and potions. Maybe that is correcting the issue encountered when using Arm/Shadow of the Destroyer.

**Comment by PrincessRTFM** [comment]
This would probably be a lot easier if I played Monk myself, but that'll take a while. I'm just making it a user-selectable combination of Arm/Shadow, Blitz, and Rockbreaker. Pick your poisons.

Also, given that change, it also sounds like Perfect Balance could change into Masterful Blitz('s variants) if you have any Beast Chakra, since PB isn't usable when you have Beast Chakra. OTOH, that could get tricky with the AoE combo, so maybe I should just remove the `MonkPerfectBalance` combo entirely...
