### ISSUE TITLE
Have you considered doing support for other languages? 

### ISSUE THREAD

**Issue by GonySue** [PrincessRTFM/XIVComboPlugin#36]
Especially some skill names can not understand

**Comment by PrincessRTFM** [comment]
Sadly, I never had the chance to learn any other languages myself, so I can't really do any translations. If someone else could help with that, I'd be willing to look into a good way to make the plugin handle different languages, but without being able to translate anything, there hasn't been much reason to.

A concern I do have is that if someone else provides translations, I'll need to wait for them when I update any text in the plugin, unless I just make it use english when no translation is available.

I'll keep this open and pinned in case someone sees it and can help translate, but keep in mind that I won't be able to compensate anyone for their time, since this is just something I do in my free time. I also won't be able to double-check translations, either.

**Comment by PrincessRTFM** [comment]
Okay, I want to update this with some more information for anyone curious:

This is technically possible, but extremely difficult. That is due to how text is used and stored for the combos, and in very small part also due to how CheapLoc (the library behind Dalamud's localisation) actually _handles_ localisation. It is _possible_ that I could implement localisation (although I'm still not sure how I would package the localisation files with the compiled plugin) for combos using the existing system of name and description to provide an english default, however the translations would need to be updated any time a combo name or description is changed, and any time a new combo is added.

Furthermore, given how CheapLoc handles localisation, it would not be able to handle this particular case. CheapLoc is designed for localisation based on a very specific implementation style, and unfortunately XIVCombo can't really be designed that way. This means I would probably also need to write my own localisation library.

While I understand that a large portion of players may not speak english, and I would personally love to make my plugin more accessible, this would be a very significant undertaking that I do not currently feel prepared for. Sadly, I have to put this fairly far down on my todo list, although I am not discarding the idea. It is my hope that I'll be able to find a reasonable approach at some point and implement that to allow for non-english-speakers to enjoy the plugin as well as making life easier for anyone whose native language is something else.
