### ISSUE TITLE
WAR - Adjustment for "Angry Beast" Feature. 

### ISSUE THREAD

**Issue by Spanglish1337** [PrincessRTFM/XIVComboPlugin#37]
Greetings,

First, I have to mention that everything is working beautifully, I have an addition to request if I may so.

If there a chance, if it is not super awful to code it in, if it does not take your time of course, only if it can be done easy enough, to have a new sub-line under "Angry beast" feature that makes Infuriate, change into Inner Chaos, to cast it, even if at 50 beast gauge? Only for Inner Chaos, under the "Nascent Chaos" buff that you receive after casting Infuriate? 

![image](https://user-images.githubusercontent.com/89648547/162359260-7d1de76f-25c8-41e7-8393-4fe13ba18df5.png)

I hope I am explaining myself correctly, if not, let me know and I will do my best to re-phrase it better.

I found out today that if you spam Infuriate and use 2 stacks in a row, you can lose a Inner Chaos cast, and it's feelsbadman.

**Comment by PrincessRTFM** [comment]
So, when Nascent Chaos is up, and you have at least 50 gauge, change Infuriate into Inner Chaos? That's easy to do, sure. But the Angry Beast feature works by changing four different hotbar actions _into_ Infuriate when your gauge is below threshold and you don't have Inner Release up, so this will make _all four_ of those actions become Inner Chaos, including Decimate, which would otherwise be Chaotic Cyclone.

Maybe this should change all four into either ST or AOE actions based on the original hotbar button? That way you won't lose out on the AOE moves when Inner Chaos is up.

**Comment by PrincessRTFM** [comment]
Update: looked at the official job guide page. IB becomes FC and SC becomes Decimate before you get access to the chaotic versions, so it's a case of A->B->C direct upgrades. One's single-target, one's AoE. I've got it set up so that each becomes only it's own upgraded version rather than both turning into Inner Chaos. If you have at least 50 gauge and you're able to use them, they upgrade, otherwise they stay at the normal version, so if you're between 72 and 80 then you only get the first one upgraded, but the other stays in case you're in a situation that calls for it.

**Comment by Spanglish1337** [comment]
Hello PrincessRTFM.

When I proposed this change, I thought it sounded a bit complicated to make it happen, and to be added as a separate option for testing.

I just tried the update now and it works beautifully, thank you so much for the change. This situation happened to me when I wanted to burst a small monster from 0 to 100 but sometimes it is hard to prevent my finger to spam a button so this helps me tremendously, thank you.
