### ISSUE TITLE
A few issues and suggestions involving various jobs

### ISSUE THREAD

**Issue by AwesomeJames2120** [PrincessRTFM/XIVComboPlugin#4]
Glad to see that this fork has made a return, since it was my go-to combo plugin before Endwalker. That being said, there's an issue at the moment involving a few jobs:

Summoner - although shiny outburst is ticked in the settings it doesn't seem to work on tri-disaster, the move outburst upgrades to. The rest of it works fine though. (And while this technically isn't an issue, having it so that topaz rite automatically swaps with mountain buster when you have titans favour would be greatly appreciated)

Sage - Doesn't have an option in the menu yet, meaning that the swift cast into raise feature isn't available for it. (Also, if you're planning on adding things to it, having the Xchole abilities swap to Rhizomata automatically when the user is out of addersgall would be fantastic)

That being said, from what I've played thus far, it seems to be working great. Looking forward to whatever else you'll be adding!

**Comment by AwesomeJames2120** [comment]
Chaos thrust and full thrust no longer change to wheeling thrust and Fang and Claw respectively. (Also, the "Dive Dive Dive!" option doesn't seem to work at all)

**Comment by PrincessRTFM** [comment]
I have (finally, at long last) gotten around to adding the swiftcast raiser for sage, and also ported over all of daemitus's fork's combos for it, and also reaper. Unfortunately, I'm getting reports that for _some_ people, certain replacers aren't working, although in at least a few cases, the problem isn't happening for everyone. Notably, these bugs seem to be happening with RPR and MNK, both of which are entirely ported versions of dae's work. Unfortunately, I can't find a _reason_ for it to be broken like this, although debugging is ongoing.

The _Dive Dive Dive!_ combo's implementation is dead simple, so it shouldn't be acting weird. Can you freshly confirm that it isn't working? It does prioritise the original action when all are available, but if you put Stardiver on your hotbar and don't have Life of the Dragon up, it _should_ become Dragonfire Dive, provided you're high enough level to use it and nothing's on cooldown.

**Comment by AwesomeJames2120** [comment]
I went to test the plugin just now, and it would appear that the Coerthan Torment combo and the "dive dive dive" combo are the only combos that work, for all the jobs i've tested. (I have only tested reaper, sage, summoner and paladin thus far)

**Comment by PrincessRTFM** [comment]
...the only combos that _do_ work? I can personally confirm that the RDM melee plus and smartcast combos definitely work for me, as do most of the MCH ones (there's I think one that I don't use), but I don't have RPR, SGE, SMN, _or_ PLD myself.

I'm going to move further discussion of the thrice-cursed inconsistent bug that's causing _some_ combos to fail for _some_ people but not others into #7 and ask that problems regarding combos that need changes or requests for new ones go into a new issue. I'll actually see them right away now too, since I finally found out that github didn't have me watching my own repo for some reason and fixed that. This is just to centralise the discission.
