### ISSUE TITLE
Feature Request - Paladin

### ISSUE THREAD

**Issue by faultlline** [PrincessRTFM/XIVComboPlugin#73]
Can you add a feature to replace Circle of Scorn with Spirits Within/Expiacion depending on which is on cooldown please? Similar to this one from Bard 
![image](https://user-images.githubusercontent.com/97929169/208967471-89f3101d-6772-4ec1-ba98-933470ee69f6.png)

**Comment by PrincessRTFM** [comment]
I can, but those three actions fit different situations. CoS and Expiacion are both reasonably close, since they both do AoE damage, although CoS is self-focused and Expiacion is target-focused for the AoE, but SW is a single-target attack instead. The secondary effects don't match either, since CoS is a DoT while the other two are MP restorers.

![Spirits Within](https://user-images.githubusercontent.com/8753564/209036167-e2f61b86-232b-4cad-9a38-f43e7a888f8c.png)
![Circle of Scorn](https://user-images.githubusercontent.com/8753564/209036086-d0af8c9f-0747-4286-a91b-b83f8e79fc0c.png)
![Expiacion](https://user-images.githubusercontent.com/8753564/209036106-bb14ade2-7012-4ddd-97cf-70f2724b2bcf.png)

Can you expand on your reasoning for this particular replacer?

**Comment by faultlline** [comment]
There's no particular reason other than "it saves a button".
In single target all three are just use off cooldown abilities with the order only mattering in the opener/reopeners. In AoE it might be problematic if you want the around self AoE from CoS to grab aggro or something and it defaults to target of SW/Expia though.

**Comment by PrincessRTFM** [comment]
Yeah, that's what I was worried about. I don't like combos that break things if you don't pay careful attention to what they've become, it feels like it defeats a lot of the purpose.

What about turning Expiacion into one of the other two if you're under level? That's useful for doing sync'd content and shouldn't break anything much if you use a self-target AoE instead of a ranged one, for example.

**Comment by faultlline** [comment]
Expiacion is the upgrade to Spirits Within so if synced you would always be switching between Spirits and Circle of Scorn. I think CoS being the default if both are up would fix the AoE problem

**Comment by PrincessRTFM** [comment]
I haven't forgotten this, the holidays have just been a little busy. Unfortunately, there's apparently some PLD changes coming in 6.3, so I'm going to hold off because that's in barely over a week and I want to see if the update changes anything. If not, I'll at least be less busy by then, so I'll be able to work on this.

**Comment by PrincessRTFM** [comment]
Okay, I've gotten the rest of the PLD stuff updated, so now I'm coming back to look at this. The only change is a minor potency tweak on Expiacion, so the previous talk still applies. SW and Expiacion are already handled by the game, so it's really just a question of turning `(A/B) -> C`, which I didn't previously realise. While I'm still not sure about the sheer potency loss, given that these are OGCDs that you basically just weave into your attacks, I think I can add some kind of smart weaving feature like I've got in a few other jobs.
