### ISSUE TITLE
Ninja Singel and AoE Smart Weave makes Cooldown longer

### ISSUE THREAD

**Issue by NikolaiDragneel** [PrincessRTFM/XIVComboPlugin#77]
Hello @all
the following skills 3026 and 3027 makes the cooldown of the Skills Ten, Chi, Jin and Ninjutsu longer as normal.

Without it is instant. Can you pls fix this if you have time?

**Comment by PrincessRTFM** [comment]
I can't reproduce this, but there was and possibly still is a known bug after patch 6.3 where ninjutsu cooldowns were too long. I'm getting the same (expected) cooldown time on all four of those actions with and without those two combos being enabled, so I don't know what to tell you. I don't think it's on my end.

Also, I don't know what you mean by the cooldown being _instant_, because that's not supposed to happen at all.
