### ISSUE TITLE
NIN Single Smart Weave

### ISSUE THREAD

**Issue by naix221** [PrincessRTFM/XIVComboPlugin#78]
I know there's an issue with ninjutsu delay introduced in the patch but this isn't just a delay.

on the first mudra single smart weave starts a full 3s global cooldown on all abilities, then it disappears for the 2nd/3rd. No issues when doing mudras with kassatsu or tenchijin. Disabling 3026 makes everything work normally with no issues. The behavior is consistent across multiple devices and with no other plugins used.

**Comment by PrincessRTFM** [comment]
What settings exactly are you using for NIN combos? Because I just tested right now on a striking dummy and no matter which of the three mudra I use, I cannot reproduce this.

**Comment by PrincessRTFM** [comment]
Update: I'm almost certain it's the vanilla cooldown bug that's responsible, because using [NoClippy](https://github.com/UnknownX7/NoClippy) from [UnknownX7's custom repo](https://github.com/UnknownX7/DalamudPluginRepo) with the [fix 6.3 mudra bug](https://user-images.githubusercontent.com/8753564/215313497-5181edfd-52e1-4aa6-b6ee-506a23160e3e.png) feature enabled (which it is by default), I cannot reproduce this at all. Turning that feature off causes the bug for me, but it doesn't matter if 3026 is enabled or not, I get the GCD issue either way.

Given that, I believe this is a _vanilla_ issue that I cannot fix. Please use the linked plugin to solve it until SE does so themselves.
