### ISSUE TITLE
Weaving for Bard

### ISSUE THREAD

**Issue by PetalTempest** [PrincessRTFM/XIVComboPlugin#80]
It seems bard is just about the only dps job to be lacking weaving functionality.
I'm inclined to assume this was done for a reason because it seems strange that it's an outlier; but I thought I would mention it just incase. I would greatly appreciate this if at all possible!

Either way thank you for your hard work! 
[<a href="https://imgur.com/AS5rBfC"><img src="https://i.imgur.com/AS5rBfC.png" title="source: imgur.com" /></a>](url)

**Comment by PrincessRTFM** [comment]
It's _technically_ done for a reason, if you count "I don't play bard so I don't know the rotation" as a reason. But if you want to contribute anything for bard then feel free! If you know C# then you can submit a PR for whatever you create. Just use the included editorconfig settings to maintain the same formatting. If you don't know C# and don't want to learn it (no judgement, programming everyone's cup of tea) then be as precise and descriptive as possible when describing what you want done. I mean _literal_ levels of precise, explain what action should be put on the hotbar, what actions it should turn into under _exactly_ what circumstances, leave nothing out.

**Comment by PetalTempest** [comment]
The one with specific conditions would be Pitch Perfect.
It is only available while the song the Wanderer's Minuet is active. 
While the song is active stacks of Repertoire build up.
Pitch Perfect should be used whenever reaching 3 stacks of Repertoire, or if the Wanderer's Minuet is about to expire. Perhaps a duration slider for customization could be helpful, as you have with various other effects. (I love that feature btw.)

The next case doesn't really have specific conditions. 
The "Bloodletter Feature" is already great. Those abilities are used on cooldown.
Pitch Perfect just takes precedence over these.

So I guess what it would ultimately look like would be something to the effect of adding/supplementing the "Bloodletter Feature" with the Pitch Perfect logic (if possible), with Pitch Perfect being the highest priority. Then using that to replace Heavy Shot/Burst Shot, and/or the "Heavy Shot into Straight Shot" option without clipping.

Thank you so much for your time and consideration!

**Comment by PrincessRTFM** [comment]
Just to make sure I understand everything, because all of the stuff currently in place for bard was essentially inherited from the original version that I forked:

- When Repertoire effect reaches three stacks _or_ Wanderer's Minuet effect is about to expire, Bloodletter should change into Pitch Perfect, prioritising that over all the existing replacements?
- To implement weaving, the Heavy Shot and Burst Shot into Straight Shot replacer should basically duplicate the Bloodletter replacer while weaving without clipping?

**Comment by PetalTempest** [comment]
Yep that sounds perfect!

**Comment by PrincessRTFM** [comment]
This would be easiest to do by just stripping the whole entire bloodletter feature and moving it all into weaving instead, so I might do that. Sorry for the delay too, there are four different effects named `The Wanderer's Minuet` so I had to log in and find a BRD main arm in order to determine which one is the right one.

**Comment by PrincessRTFM** [comment]
Okay, I don't really play BRD but I grabbed a level boost for testing purposes before EW, so I've got something that _looks_ like it works well (to my entirely untrained eye) at level 70. I stripped a couple of things that made no sense to me and/or were duplicated elsewhere, hopefully the new set is good:
![image](https://user-images.githubusercontent.com/8753564/229372062-08797d57-c455-4dd5-b922-bcda04cc90d1.png)

The weaving options should be self-explanatory, and are checked in the order shown. The first one that passes (for everything but Pitch Perfect, the check is just "can you use this") will be applied, so if everything's up and you're high enough level, it'll go Pitch Perfect -> Battle Voice -> Raging Strikes -> Sidewinder -> Empyreal Arrow -> Bloodletter / Rain of Death (because they share charges).

Heavy Jaws is similar to Iron Bites in that it's functionally a DoT saver, but it replaces Heavy/Burst Shot. It _should_ be intelligent about your level (so if you can't use Iron Jaws, it'll use the DoTs directly) and it'll prioritise Windbite/Stormbite for the slightly higher DoT potency. Iron Bites is a pure rename of the existing feature that does this.

Rain of Shadows turns Shadowbite into Rain of Death when weaving _or_ when under level for Shadowbite. Both are targeted AoE attacks, so this'll make one button into a "hit my target and everything near it" button.

Empyreal Sidewinder is the old Sidewinder Feature except it replaces _both_ actions with each other depending on what's available. If both are up, the button will prioritise whichever you originally put on your hotbar, so you can actually have access to both at the same time while still getting the fallback effect.

I think that's everything I changed. I'm about to release this now, but let me know if I fucked something up, either conceptually or in the internal logic.

**Comment by PrincessRTFM** [comment]
Also it turned out I didn't need the effect because the relevant information was actually in the job gauge, lol. The delay, as it happened, was unnecessary. My bad!

**Comment by PetalTempest** [comment]
OMG it's _**awesome!!!**_
Thank you soooo much!!!
[<a href="https://imgur.com/cWtWr76"><img src="https://i.imgur.com/cWtWr76.png" title="source: imgur.com" /></a>](url)

**Comment by PetalTempest** [comment]
Oh! I just noticed one potential issue. 
Is there a way to prioritize the new "Heavy Jaws" over the "Apex Arrow Feature" so that dots don't drop off while Apex Arrow/Blast Arrow are being cast?

**Comment by PrincessRTFM** [comment]
Changed and pushed!

**Comment by PetalTempest** [comment]
You are a wizard!

**Comment by PrincessRTFM** [comment]
Glad it's all working well!
