### ISSUE TITLE
Scholar features 

### ISSUE THREAD

**Issue by Nyakaze** [PrincessRTFM/XIVComboPlugin#84]
Heey! 💜

Could you consider adding some features like Sage has?

1. Ruin/Broil1-4 would become Ruin 2 while moving.
2. Ruin/Broil1-4 would become Lucid Dreaming when under a threshhold. (Like on Sage)

I know the title says "Scholar", but I think it would be cool maybe in general to have the option to weave Lucid Dreaming in all the classes. (Like on Sage)

Thank you for your consideration you're doing an amazing job!💜🌸

**Comment by PrincessRTFM** [comment]
I can definitely do both(/all) of that, but be advised that I only have two casters (Sage and Red Mage) so I can't _test_ these things myself. I can look through the code (which I inherited from the original project I forked) and the official action guide pages to try and figure out what to weave LD _onto_ for other casters, but since I don't actually know them, I might not get it right.
