### ISSUE TITLE
MNK Feature Requests

### ISSUE THREAD

**Issue by Evolutious** [PrincessRTFM/XIVComboPlugin#9]
Good day PrincessRTFM! First off, thank you for creating this fork and expanding this plugin to help with the vast amount of buttons in FFXIV ;)

With MNK I see you have a several for AoE actions but no ST actions. Do you have any plans to add any of those?

A few that I think would be useful:
- 'Dragon Kick' changes into 'Bootshine' if you have the 'Leaden Fist' buff
- 'Twin Snakes' changes into 'True Strike' if you have the 'Disciplined Fist' buff
- 'Demolish' changes into 'Snap Punch' if your target has the 'Demolish' debuff

All of the 'actions' that would change into another 'action' above you learn at lower job levels, so you would not have any issues with lower level players but it would eliminate 3 more buttons.

Thoughts?

**Comment by PrincessRTFM** [comment]
Good day, and I'm glad people like my fork!

As for MNK, I actually don't _play_ MNK (and don't even have it unlocked), and that's why I haven't got nearly as many features for it as for something like RDM, which is my main. I just don't know what's useful, needed, or even sensible, until someone like you tells me. But that's why I'm open to requests, and why I make an effort to meet any reasonable and politely-made ones!

From what you're saying, the only condition for each of the changes is a simple status-effect-check, since all of the secondaries (which the primary turns into) are learned at _lower_ levels, meaning that if you can use the primary (which is what you put on your hotbar) then you can use the secondary as well. If I'm understanding that right, those would be easy to implement, and could even be made to change the same way if you're underlevel for the later stuff.

Can you confirm that there are no other conditions that should be checked on those? If so, I can probably have them implemented and released today.

**Comment by Evolutious** [comment]
That is it!

For edification purposes; Basically, most all melee jobs operate on a 1/2/3 rotation where you use one ability and it interacts with a second ability. Using that second ability then interacts with a third ability and that third ability interacts with the first. In the case on MNK, you have 2 sets of 1/2/3 where 1 set are lower potency "maintenance" buff/debuff actions while the other set are your primary damage dealers.

Dragon Kick gives you the Leaden Fist buff that increases the potency of your next Bootshine, but you wont use Bootshine until after you go back through your rotation since both Dragon Kick and Bootshine are "1"s in the rotation.

Twin Snakes give you the Disciplined Fist buff, which makes you do increased damage while it is active. True Strike simply just has a higher potency with both Twin Snakes and True Strike being "2"s in the rotation.

Demolish applies a DoT to your target for 18s while Snap Puch is a higher potency single hit. You want to apply the DoT to your target if/when it drops off since the total potency of Demolish (plus its DoT) will be higher then Snap Punch while both are "3"s in the rotation.

**Comment by Evolutious** [comment]
Hey there! Thank you for the add, but I did want to let you know that something is not right with the 'Twin Snakes to True Strike Feature'. It looks like you may be using the wrong action ID for True Strike as it does not allow the action to be used when it gets flipped over. Can you check that you have the right action ID please?

This is what Twin Snakes is being changed into: https://gyazo.com/003204829d9cdf09362e40481403d2f4 (note the indication at the bottom that it cannot be placed on a bar and the combo action with Bootshine).

For comparison, here is the actual True Strike action tooltip: https://gyazo.com/df1ab0766d9af7fb19713959aacd66dc

It just sems to me you are using the wrong action ID in your swap for this one. the other two work perfectly!

**Comment by PrincessRTFM** [comment]
Pushed a fix, should be working as soon as the auto-build is done. Sorry about that!

**Comment by Evolutious** [comment]
Confirmed fixed! Thank you again!
