### ISSUE TITLE
Dragoon - combine 2 combos

### ISSUE THREAD

**Issue by Theletha** [PrincessRTFM/XIVComboPlugin#94]
Hi

Would it be possible to somehow combine Debug 2202 with Debug 2201. So we get 1 action button to self buff (power surge)   and then apply target Dot (from chaos thrust) then at the end move into "Fang and Claw" and "Wheeling Thrust" ending with "Raiden Thrust".

So the priority would be something like this:
Power surge buff (depending on the buff threshold setting in Debug 2212)
Chaos Thrust Dot on current target (maybe add a threshold setting for this too?)
(if any below is up ignore above until combo is finished)
Fang and claw into Wheeling Thrust 
Raiden Thrust

**Comment by PrincessRTFM** [comment]
I haven't played in a while but my subscription should still be going, so I'll take a look and see what I can do! It might not be possible to do the configuration _exactly_ as you're saying because of the internal implementation details, but just from reading your request, it should be doable.

**Comment by Theletha** [comment]
Ofc if its not possible then it is what it is! thanks for taking a look at it!

**Comment by PrincessRTFM** [comment]
It's the configuration that would be the (potential) issue, since that whole system is designed to link each configurable value to a single combo, but even if I can't arrange a workaround, it would just mean rearranging the combo settings for those things, which should be doable. It just might be tricky to get the UI side playing nicely, is all...

Also, I appreciate the clarity of the priority description you provided! Listing the checks in order and specifying in advance that you want in-progress combos to be completed before the other things are entered gave me what should be all of the information I need, no followup questions required.

**Comment by PrincessRTFM** [comment]
Okay, finally getting to look at the combos themselves. Now, I don't play DRG so I'm trying to put the pieces together off the [official job guide page](https://na.finalfantasyxiv.com/jobguide/dragoon/), which isn't great for trying to understand how the job works. As best I'm understanding right now, you want the priority to be something like...

- if Power Surge buff is not up or is below _X_ seconds left, execute the Chaos Thrust chain for the damage buff
	- skip this if already mid-way through a skill chain and complete that first
- if the current target doesn't have the Chaos Thrust DoT on them with at least _X_ seconds left, execute the Chaos Thrust chain for the DoT
	- follow up with Wheeling Thrust, then Fang and Claw, then Raiden Thrust, using the buff chain
	- skip this if already mid-way through a skill chain and complete that first
- execute the Full Thrust chain
	- follow up with Fang and Claw, then Wheeling Thrust, then Raiden Thrust, using the buff chain

Have I got that all correct? Also, what action do you want replaced with this combo - as in, what button do you want to put on your hotbar to use this?

**Comment by Theletha** [comment]
outstanding! looks great!
The action to replace could be "True Thrust " since its the first action for the combo so it makes sense.
