### ISSUE TITLE
Request: Dancer Combo Standard/Technical Step

### ISSUE THREAD

**Issue by RedactedHash** [PrincessRTFM/XIVComboPlugin#96]
Would it be possible to add a combo for Technical Step that switches with the following logic?-
  1. Technical Finish when active
  2. Standard Finish when active
  3. Standard Step when Technical Step is Unavailable or on Cooldown
  4. Technical Step

Additionally, an option for replacing Standard Step might have the following logic-
  1. Technical Finish when active
  2. Standard Finish when active
  3. Technical Step when available and Standard Finish buff time remaining > 33
  4. Standard Step

I think this would be a very very useful set of button combos to have if you are willing :-D

**Comment by RedactedHash** [comment]
Hello, sorry to be a bother... these don't seem to function... either...

I'm trying to think through the logic again as stated and see what I messed up so please bear with me...

am I misunderstanding how the mod functions and it isn't regularly polling for what the icon should be for the button based on state changes? what I had in my head is that... 

on standard step checking what icon/action it should use:
    `if (technicalStep.available && techncialStep.cooldown == 0  && standardsStep.cooldown > 33) technicalStep;`

on technical step checking what icon/action it should use:
    `if ((technicalStep.available == false  || technicalStep is on cooldown) && standardStep.cooldown <= 33) standardStep;`

**Comment by PrincessRTFM** [comment]
The way the plugin works is that it "hooks" the game's own native function used by traits to upgrade actions, which is called on every action. The plugin then does its own logic in order to tell the game "this action should be this other action right now", but the game is what handles the actual replacement.

As for the rest, here's the logic it's using, in the order the checks are done:

- If your level is high enough for TS, you have Smart Standard Step enabled, TS is _off_ cooldown, and SS has more than three seconds left on its cooldown, _both_ buttons become TS.
  - When replacing the TS button, there is effectively no change - it was already TS. Therefore, this only actually "affects" the SS button.
- If your level is high enough for TS, you have Smart Tech Step enabled, and TS is _on_ cooldown, _both_ buttons become SS.
  - When replacing the SS button, there's effectively no change - it was already SS.
- If your level is too low for Tech Step, and you've enabled the Smart Tech Step combo, _both_ buttons become SS.
  - When replacing the SS button, there's effectively no change.
- Finally, if all else fails, the actions aren't touched.

The end result of this should be that when the function is run on TS, it's unchanged _unless_ it's either unavailable or not ready. Those are the only two conditions that should ever turn it into SS. Likewise, when run over SS, the function should _only_ change it when TS is available and ready _and_ SS has move than three seconds of cooldown left.

Looking over it, I can't find the problem. Are you certain that you enabled both combos in `/pcombo`, that you've placed Standard Step and/or Technical Step on your hotbar, and that you aren't running any other combo plugin forks?

**Comment by PrincessRTFM** [comment]
While I did just add a minor fix to make Tillana accessible again (oops) and show the original button when _both_ are on cooldown for the purposes of cooldown tracking, I cannot reproduce the failure of the actual purpose of the combos. They work exactly as expected and described for me. Please make sure you have combos 55, 56, and 57 all enabled.

**Comment by RedactedHash** [comment]
It is a misunderstanding in what function you were hooking... the use case I had dreamt of was that (I still prefer to do the steps manually) is that normally I have a macro as my "Technical Step" that lives on my where it it `/ac`'s Technical Step and then tries Standard Step... so that if I'm in my AOE rotation I don't need to flip back to standard step to hit it unless the cooldown on standard is < 33 seconds and shouldn't do technical step until I complete a standard step first. My dream behavior would be that technical step defaults back to standard step any time it is better to use it. And then with the standard combo it would always show standard step unless technical step was specifically available and the cooldown on standard step is high enough (`>33`s) that it will show and choose technical step instead.

I hope this makes sense. 

![example](https://github.com/PrincessRTFM/XIVComboPlugin/assets/1486324/c5059f92-beb7-45ee-bec9-e04f3161edb0)

**Comment by PrincessRTFM** [comment]
Ah. I think I understand. You wanted it to only change into the Step and Finish actions and still let you do the dance steps normally? I can do that. Is the rest of the logic (for which one to choose) working properly in-game?
