### ISSUE TITLE
Request: Sprint -> Peloton

### ISSUE THREAD

**Issue by fchud** [PrincessRTFM/XIVComboPlugin#97]
Pretty much title.

would be nice to:
substitute Sprint with Peloton when the first one is on cooldown and the second one is available.

and:
in party/dungeon could be a Sprint (if available) straight followed by Peloton (if available).

**Comment by PrincessRTFM** [comment]
Unfortunately, neither of those is subject to the same replacement functionality as combat actions, which means that the hook XivCombo uses can't actually modify them. I already tried a while back. Similarly, DoH actions don't work either.

If you know of another fork that does this, let me know and I can see how they did it, but otherwise I'm afraid this just isn't something I can add.

**Comment by fchud** [comment]
that's cool, Dog.

i still have macro )
Sprint > W1s > Peloton.

Really just wanted an Icon w/o gear.
who would've guessed it is that complicated.

thanx anyway. cheers :)
